#[Project Euler](https://projecteuler.net/archives)

In [ ]:
from scipy.special import comb
import math
import pandas as pd
from google.colab import files
import io
import itertools
from itertools import permutations

**Problem 1: Multiples of 3 or 5**

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [ ]:
sum = 0

for num in range(1,1000):
  if ((num % 3 == 0) or (num % 5 == 0)):
    sum += num

sum

233168

**Problem 2: Even Fibonacci numbers**

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [ ]:
sum = 0
a = 1  # Represents the current Fibonacci number being processed
b = 2  # Represents the next Fibonacci number in the sequence

while a <= 4000000:
  if (a % 2 == 0):
	  sum += a
  a, b = b, a + b

sum

4613732

**Problem 3: Largest prime factor**

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [ ]:
# Didn't understand solutions on the internet

**Problem 4: Largest palindrome product**

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [ ]:
# 6 digit palindrome with factors as two 3-digit numbers
product = 0
products = []

for i in range(100, 1000):
  for j in range(100, 1000):
    product = i * j
    if (product == int(str(product)[::-1])):
      products.append(product)

print(max(products))

906609

**Problem 5: Smallest multiple**

2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [ ]:
# Maximum powers of each prime no. till 20: 2^4, 3^2, 5, 7, 11, 13, 17, 19 => 5, 7, 9, 11, 13, 16, 17, 19
5 * 7 * 9 * 11 * 13 * 16 * 17 * 19

232792560

**Problem 6: Sum square difference**

The sum of the squares of the first ten natural numbers is,

1^2 + 2^2 + ... + 10^2 = 385

The square of the sum of the first ten natural numbers is,

(1 + 2 + ... + 10)^2 = 55^2 = 3025

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is

3025 - 385 = 2640

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [ ]:
sum_of_squares = sum = 0

for num in range(1,101):
  sum_of_squares += num ** 2
  sum += num

square_of_sum = sum ** 2
difference = square_of_sum - sum_of_squares

difference

25164150

**Problem 7: 10001st prime**

By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?

In [ ]:
index = 0
num = 2

while(True):
  def is_prime(n):
    for i in range(2, n//2+1):
      if (n % i == 0):
        return False
    return True

  if is_prime(num):
    index += 1

  if (index == 10001):
    break
  num += 1

num

104743

**Problem 8: Largest product in a series**

The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.

73167176531330624919225119674426574742355349194934
96983520312774506326239578318016984801869478851843
85861560789112949495459501737958331952853208805511
12540698747158523863050715693290963295227443043557
66896648950445244523161731856403098711121722383113
62229893423380308135336276614282806444486645238749
30358907296290491560440772390713810515859307960866
70172427121883998797908792274921901699720888093776
65727333001053367881220235421809751254540594752243
52584907711670556013604839586446706324415722155397
53697817977846174064955149290862569321978468622482
83972241375657056057490261407972968652414535100474
82166370484403199890008895243450658541227588666881
16427171479924442928230863465674813919123162824586
17866458359124566529476545682848912883142607690042
24219022671055626321111109370544217506941658960408
07198403850962455444362981230987879927244284909188
84580156166097919133875499200524063689912560717606
05886116467109405077541002256983155200055935729725
71636269561882670428252483600823257530420752963450

Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?

In [ ]:
# Solution 1
num = 7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450
products = []
num_str = str(num)

for i in range(len(num_str)-12):
  product = int(num_str[i]) * int(num_str[i+1]) * int(num_str[i+2]) * int(num_str[i+3]) * int(num_str[i+4]) * int(num_str[i+5]) * int(num_str[i+6]) *\
    int(num_str[i+7]) * int(num_str[i+8]) * int(num_str[i+9]) * int(num_str[i+10]) * int(num_str[i+11]) * int(num_str[i+12])
  products.append(product)

max(products)

23514624000

In [ ]:
# Solution 2
num = 7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450
products = []
num_str = str(num)

for i in range(len(num_str)-12):
  product = int(num_str[i])

  for j in range(1,13):
    product *= int(num_str[i+j])
  products.append(product)

max(products)

23514624000

**Problem 9: Special Pythagorean triplet**

A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

a^2 + b^2 = c^2

For example, 3^2 + 4^2 = 9 + 16 = 25 = 52.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

In [ ]:
# a < 333 since a < b < c, a + b + c = 1000 and a,b,c are natural numbers
# Then b < 500 because min(a) = 1 and that will imply b + c = 999
for a in range(1,333):
  for b in range(a+1,500):
    c = 1000 - a - b
    if (a**2 + b**2 == c**2):
      print(a * b * c)

31875000

**Problem 10: Summation of primes**

The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.

In [ ]:
sum = 0

for i in range(2, 2000000):
  def is_prime(n):
    for i in range(2, int(n**0.5) + 1):
      if (n % i == 0):
        return False
    return True

  if is_prime(i):
    sum += i

sum

142913828922

**Problem 11: Largest product in a grid**

In the 20×20 grid below, four numbers along a diagonal line have been marked in red.

08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48

The product of these numbers is 26 × 63 × 78 × 14 = 1788696.

What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20×20 grid?

In [ ]:
grid = [
	[ 8, 2,22,97,38,15, 0,40, 0,75, 4, 5, 7,78,52,12,50,77,91, 8],
	[49,49,99,40,17,81,18,57,60,87,17,40,98,43,69,48, 4,56,62, 0],
	[81,49,31,73,55,79,14,29,93,71,40,67,53,88,30, 3,49,13,36,65],
	[52,70,95,23, 4,60,11,42,69,24,68,56, 1,32,56,71,37, 2,36,91],
	[22,31,16,71,51,67,63,89,41,92,36,54,22,40,40,28,66,33,13,80],
	[24,47,32,60,99, 3,45, 2,44,75,33,53,78,36,84,20,35,17,12,50],
	[32,98,81,28,64,23,67,10,26,38,40,67,59,54,70,66,18,38,64,70],
	[67,26,20,68, 2,62,12,20,95,63,94,39,63, 8,40,91,66,49,94,21],
	[24,55,58, 5,66,73,99,26,97,17,78,78,96,83,14,88,34,89,63,72],
	[21,36,23, 9,75, 0,76,44,20,45,35,14, 0,61,33,97,34,31,33,95],
	[78,17,53,28,22,75,31,67,15,94, 3,80, 4,62,16,14, 9,53,56,92],
	[16,39, 5,42,96,35,31,47,55,58,88,24, 0,17,54,24,36,29,85,57],
	[86,56, 0,48,35,71,89, 7, 5,44,44,37,44,60,21,58,51,54,17,58],
	[19,80,81,68, 5,94,47,69,28,73,92,13,86,52,17,77, 4,89,55,40],
	[ 4,52, 8,83,97,35,99,16, 7,97,57,32,16,26,26,79,33,27,98,66],
	[88,36,68,87,57,62,20,72, 3,46,33,67,46,55,12,32,63,93,53,69],
	[ 4,42,16,73,38,25,39,11,24,94,72,18, 8,46,29,32,40,62,76,36],
	[20,69,36,41,72,30,23,88,34,62,99,69,82,67,59,85,74, 4,36,16],
	[20,73,35,29,78,31,90, 1,74,31,49,71,48,86,81,16,23,57, 5,54],
	[ 1,70,54,71,83,51,54,69,16,92,33,48,61,43,52, 1,89,19,67,48],
]

products = []

# Calculating horizontal products
for i in range(20):
  for j in range(17):
    horizontal_product = grid[i][j] * grid[i][j+1] * grid[i][j+2] * grid[i][j+3]
    if (horizontal_product != 0):
      products.append(horizontal_product)

# 318 such products
# len(products)

# Calculating vertical products
for i in range(20):
  for j in range(17):
    vertical_product = grid[j][i] * grid[j+1][i] * grid[j+2][i] * grid[j+3][i]
    if (vertical_product != 0):
      products.append(vertical_product)

# 322 such products, so total = 640
# len(products)

# Calculating left diagonals products
# grid[0][16] * grid[1][17] * grid[2][18] * grid[3][19]
# grid[0][15] * grid[1][16] ...
# grid[0][0] * grid[1][1] ...
# grid[1][0] * grid[2][1] ...
# grid[16][0] * grid[17][1] * grid[18][2] * grid[19][3]
for i in range(17):
  for j in range(16,-1,-1):
    left_diagonals_product = grid[i][j] * grid[i+1][j+1] * grid[i+2][j+2] * grid[i+3][j+3]
    if (left_diagonals_product != 0):
      products.append(left_diagonals_product)

# 272 such products, so total = 912
# len(products)

# Calculating right diagonals products
# grid[0][3] * grid[1][2] * grid[2][1] * grid[3][0]
# grid[0][4] * grid[1][3] ...
# grid[0][19] * grid[1][18] ...
# grid[15][19] * grid[16][18] ...
# grid[16][19] * grid[17][18] * grid[18][17] * grid[19][16]
for i in range(17):
  for j in range(3,20):
    right_diagonals_product = grid[i][j] * grid[i+1][j-1] * grid[i+2][j-2] * grid[i+3][j-3]
    if (right_diagonals_product != 0):
      products.append(right_diagonals_product)

# 272 such products, so total = 1184
# len(products)

max(products)

70600674

**Problem 12: Highly divisible triangular number**

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1<br>
 3: 1,3<br>
 6: 1,2,3,6<br>
10: 1,2,5,10<br>
15: 1,3,5,15<br>
21: 1,3,7,21<br>
28: 1,2,4,7,14,28<br>

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

In [ ]:
def is_triangular(n):
  for i in range(1, n+1):
    if (i*(i+1)/2 == n):
      return True

  return False

# is_triangular(28) # Testing

def divisor_count(n) :
  count = 0

  for i in range(1, int(n**0.5) + 1):
    if (n % i == 0):
      # If divisors are equal, count only one
      if (n / i == i):
        count += 1
      # Otherwise count both
      else:
        count += 2

  return count

# divisor_count(28) # Testing

i = num = 1

while True:
  if (is_triangular(num) and divisor_count(num) > 500):
    break

  i += 1
  num += i

print(num)

76576500

**Problem 13: Large sum**

Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.

37107287533902102798797998220837590246510135740250
46376937677490009712648124896970078050417018260538
74324986199524741059474233309513058123726617309629
91942213363574161572522430563301811072406154908250
23067588207539346171171980310421047513778063246676
89261670696623633820136378418383684178734361726757
28112879812849979408065481931592621691275889832738
44274228917432520321923589422876796487670272189318
47451445736001306439091167216856844588711603153276
70386486105843025439939619828917593665686757934951
62176457141856560629502157223196586755079324193331
64906352462741904929101432445813822663347944758178
92575867718337217661963751590579239728245598838407
58203565325359399008402633568948830189458628227828
80181199384826282014278194139940567587151170094390
35398664372827112653829987240784473053190104293586
86515506006295864861532075273371959191420517255829
71693888707715466499115593487603532921714970056938
54370070576826684624621495650076471787294438377604
53282654108756828443191190634694037855217779295145
36123272525000296071075082563815656710885258350721
45876576172410976447339110607218265236877223636045
17423706905851860660448207621209813287860733969412
81142660418086830619328460811191061556940512689692
51934325451728388641918047049293215058642563049483
62467221648435076201727918039944693004732956340691
15732444386908125794514089057706229429197107928209
55037687525678773091862540744969844508330393682126
18336384825330154686196124348767681297534375946515
80386287592878490201521685554828717201219257766954
78182833757993103614740356856449095527097864797581
16726320100436897842553539920931837441497806860984
48403098129077791799088218795327364475675590848030
87086987551392711854517078544161852424320693150332
59959406895756536782107074926966537676326235447210
69793950679652694742597709739166693763042633987085
41052684708299085211399427365734116182760315001271
65378607361501080857009149939512557028198746004375
35829035317434717326932123578154982629742552737307
94953759765105305946966067683156574377167401875275
88902802571733229619176668713819931811048770190271
25267680276078003013678680992525463401061632866526
36270218540497705585629946580636237993140746255962
24074486908231174977792365466257246923322810917141
91430288197103288597806669760892938638285025333403
34413065578016127815921815005561868836468420090470
23053081172816430487623791969842487255036638784583
11487696932154902810424020138335124462181441773470
63783299490636259666498587618221225225512486764533
67720186971698544312419572409913959008952310058822
95548255300263520781532296796249481641953868218774
76085327132285723110424803456124867697064507995236
37774242535411291684276865538926205024910326572967
23701913275725675285653248258265463092207058596522
29798860272258331913126375147341994889534765745501
18495701454879288984856827726077713721403798879715
38298203783031473527721580348144513491373226651381
34829543829199918180278916522431027392251122869539
40957953066405232632538044100059654939159879593635
29746152185502371307642255121183693803580388584903
41698116222072977186158236678424689157993532961922
62467957194401269043877107275048102390895523597457
23189706772547915061505504953922979530901129967519
86188088225875314529584099251203829009407770775672
11306739708304724483816533873502340845647058077308
82959174767140363198008187129011875491310547126581
97623331044818386269515456334926366572897563400500
42846280183517070527831839425882145521227251250327
55121603546981200581762165212827652751691296897789
32238195734329339946437501907836945765883352399886
75506164965184775180738168837861091527357929701337
62177842752192623401942399639168044983993173312731
32924185707147349566916674687634660915035914677504
99518671430235219628894890102423325116913619626622
73267460800591547471830798392868535206946944540724
76841822524674417161514036427982273348055556214818
97142617910342598647204516893989422179826088076852
87783646182799346313767754307809363333018982642090
10848802521674670883215120185883543223812876952786
71329612474782464538636993009049310363619763878039
62184073572399794223406235393808339651327408011116
66627891981488087797941876876144230030984490851411
60661826293682836764744779239180335110989069790714
85786944089552990653640447425576083659976645795096
66024396409905389607120198219976047599490197230297
64913982680032973156037120041377903785566085089252
16730939319872750275468906903707539413042652315011
94809377245048795150954100921645863754710598436791
78639167021187492431995700641917969777599028300699
15368713711936614952811305876380278410754449733078
40789923115535562561142322423255033685442488917353
44889911501440648020369068063960672322193204149535
41503128880339536053299340368006977710650566631954
81234880673210146739058568557934581403627822703280
82616570773948327592232845941706525094512325230608
22918802058777319719839450180888072429661980811197
77158542502016545090413245809786882778948721859617
72107838435069186155435662884062257473692284509516
20849603980134001723930671666823555245252804609722
53503534226472524250874054075591789781264330331690

In [ ]:
nums = [
  37107287533902102798797998220837590246510135740250,
  46376937677490009712648124896970078050417018260538,
  74324986199524741059474233309513058123726617309629,
  91942213363574161572522430563301811072406154908250,
  23067588207539346171171980310421047513778063246676,
  89261670696623633820136378418383684178734361726757,
  28112879812849979408065481931592621691275889832738,
  44274228917432520321923589422876796487670272189318,
  47451445736001306439091167216856844588711603153276,
  70386486105843025439939619828917593665686757934951,
  62176457141856560629502157223196586755079324193331,
  64906352462741904929101432445813822663347944758178,
  92575867718337217661963751590579239728245598838407,
  58203565325359399008402633568948830189458628227828,
  80181199384826282014278194139940567587151170094390,
  35398664372827112653829987240784473053190104293586,
  86515506006295864861532075273371959191420517255829,
  71693888707715466499115593487603532921714970056938,
  54370070576826684624621495650076471787294438377604,
  53282654108756828443191190634694037855217779295145,
  36123272525000296071075082563815656710885258350721,
  45876576172410976447339110607218265236877223636045,
  17423706905851860660448207621209813287860733969412,
  81142660418086830619328460811191061556940512689692,
  51934325451728388641918047049293215058642563049483,
  62467221648435076201727918039944693004732956340691,
  15732444386908125794514089057706229429197107928209,
  55037687525678773091862540744969844508330393682126,
  18336384825330154686196124348767681297534375946515,
  80386287592878490201521685554828717201219257766954,
  78182833757993103614740356856449095527097864797581,
  16726320100436897842553539920931837441497806860984,
  48403098129077791799088218795327364475675590848030,
  87086987551392711854517078544161852424320693150332,
  59959406895756536782107074926966537676326235447210,
  69793950679652694742597709739166693763042633987085,
  41052684708299085211399427365734116182760315001271,
  65378607361501080857009149939512557028198746004375,
  35829035317434717326932123578154982629742552737307,
  94953759765105305946966067683156574377167401875275,
  88902802571733229619176668713819931811048770190271,
  25267680276078003013678680992525463401061632866526,
  36270218540497705585629946580636237993140746255962,
  24074486908231174977792365466257246923322810917141,
  91430288197103288597806669760892938638285025333403,
  34413065578016127815921815005561868836468420090470,
  23053081172816430487623791969842487255036638784583,
  11487696932154902810424020138335124462181441773470,
  63783299490636259666498587618221225225512486764533,
  67720186971698544312419572409913959008952310058822,
  95548255300263520781532296796249481641953868218774,
  76085327132285723110424803456124867697064507995236,
  37774242535411291684276865538926205024910326572967,
  23701913275725675285653248258265463092207058596522,
  29798860272258331913126375147341994889534765745501,
  18495701454879288984856827726077713721403798879715,
  38298203783031473527721580348144513491373226651381,
  34829543829199918180278916522431027392251122869539,
  40957953066405232632538044100059654939159879593635,
  29746152185502371307642255121183693803580388584903,
  41698116222072977186158236678424689157993532961922,
  62467957194401269043877107275048102390895523597457,
  23189706772547915061505504953922979530901129967519,
  86188088225875314529584099251203829009407770775672,
  11306739708304724483816533873502340845647058077308,
  82959174767140363198008187129011875491310547126581,
  97623331044818386269515456334926366572897563400500,
  42846280183517070527831839425882145521227251250327,
  55121603546981200581762165212827652751691296897789,
  32238195734329339946437501907836945765883352399886,
  75506164965184775180738168837861091527357929701337,
  62177842752192623401942399639168044983993173312731,
  32924185707147349566916674687634660915035914677504,
  99518671430235219628894890102423325116913619626622,
  73267460800591547471830798392868535206946944540724,
  76841822524674417161514036427982273348055556214818,
  97142617910342598647204516893989422179826088076852,
  87783646182799346313767754307809363333018982642090,
  10848802521674670883215120185883543223812876952786,
  71329612474782464538636993009049310363619763878039,
  62184073572399794223406235393808339651327408011116,
  66627891981488087797941876876144230030984490851411,
  60661826293682836764744779239180335110989069790714,
  85786944089552990653640447425576083659976645795096,
  66024396409905389607120198219976047599490197230297,
  64913982680032973156037120041377903785566085089252,
  16730939319872750275468906903707539413042652315011,
  94809377245048795150954100921645863754710598436791,
  78639167021187492431995700641917969777599028300699,
  15368713711936614952811305876380278410754449733078,
  40789923115535562561142322423255033685442488917353,
  44889911501440648020369068063960672322193204149535,
  41503128880339536053299340368006977710650566631954,
  81234880673210146739058568557934581403627822703280,
  82616570773948327592232845941706525094512325230608,
  22918802058777319719839450180888072429661980811197,
  77158542502016545090413245809786882778948721859617,
  72107838435069186155435662884062257473692284509516,
  20849603980134001723930671666823555245252804609722,
  53503534226472524250874054075591789781264330331690
]

sum = 0

for num in nums:
  sum += num

int(str(sum)[:10])

5537376230

**Problem 14: Longest Collatz sequence**

The following iterative sequence is defined for the set of positive integers:

n → n/2 (n is even)<br>
n → 3n + 1 (n is odd)

Using the rule above and starting with 13, we generate the following sequence:

13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1

It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.

Which starting number, under one million, produces the longest chain?

**NOTE**: Once the chain starts the terms are allowed to go above one million.

In [ ]:
# Sequence                                  Count
# 2 -> 1                                      2
# 3 -> 10 -> 5 -> 16 -> 8 -> 4 -> 2 -> 1      8
# 4 -> 2 -> 1                                 3

def collatz_len(m):
  if m == 1:
    return 1
  if m % 2 == 0:
    n = m // 2
  else:
    n = 3 * m + 1
  return collatz_len(n) + 1

max_collatz_len_index = 1
max_collatz_len = 1

for i in range(2, 1000000):
  if collatz_len(i) > max_collatz_len:
    max_collatz_len = collatz_len(i)
    max_collatz_len_index = i

max_collatz_len_index

837799

**Problem 15: Lattice paths**

Starting in the top left corner of a 2×2 grid, and only being able to move to the right and down, there are exactly 6 routes to the bottom right corner.

How many such routes are there through a 20×20 grid?

In [ ]:
int(comb(40, 20))

137846528820

**Problem 16: Power digit sum**

2^15 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.

What is the sum of the digits of the number 2^1000?

In [ ]:
# 32768 // 10**4, 2768 // 10**3, 768 // 10**2, 68 // 10**1, 8 // 10**0
# (3, 2, 7, 6, 8)

# math.floor(math.log(32768, 10))
# 4

# 32768 % 10**4
# 2768

def sum_of_digits(n):
  num = n
  sum = 0
  i = math.floor(math.log10(n))

  while i > -1:
    sum += num // 10**i
    num %= 10**i
    i -= 1

  return sum

sum_of_digits(2**1000)

1366

**Problem 17: Number letter counts**

If the numbers 1 to 5 are written out in words: one, two, three, four, five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.

If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, how many letters would be used?


**NOTE:** Do not count spaces or hyphens. For example, 342 (three hundred and forty-two) contains 23 letters and 115 (one hundred and fifteen) contains 20 letters. The use of "and" when writing out numbers is in compliance with British usage.

In [ ]:
def compute():
	ans = sum(len(to_english(i)) for i in range(1, 1001))
	return str(ans)

def to_english(n):
	if 0 <= n < 20:
		return ONES[n]
	elif 20 <= n < 100:
		return TENS[n // 10] + (ONES[n % 10] if (n % 10 != 0) else "")
	elif 100 <= n < 1000:
		return ONES[n // 100] + "hundred" + (("and" + to_english(n % 100)) if (n % 100 != 0) else "")
	elif 1000 <= n < 1000000:
		return to_english(n // 1000) + "thousand" + (to_english(n % 1000) if (n % 1000 != 0) else "")
	else:
		raise ValueError()


ONES = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine",
        "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen"]
TENS = ["", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"]

if __name__ == "__main__":
	print(compute())

TypeError: ignored

**Problem 18: Maximum path sum I**

By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.

3<br>
7 4<br>
2 4 6<br>
8 5 9 3

That is, 3 + 7 + 4 + 9 = 23.

Find the maximum total from top to bottom of the triangle below:

75<br>
95 64<br>
17 47 82<br>
18 35 87 10<br>
20 04 82 47 65<br>
19 01 23 75 03 34<br>
88 02 77 73 07 63 67<br>
99 65 04 28 06 16 70 92<br>
41 41 26 56 83 40 80 70 33<br>
41 48 72 33 47 32 37 16 94 29<br>
53 71 44 65 25 43 91 52 97 51 14<br>
70 11 33 28 77 73 17 78 39 68 17 57<br>
91 71 52 38 17 14 91 43 58 50 27 29 48<br>
63 66 04 68 89 53 67 30 73 16 69 87 40 31<br>
04 62 98 27 23 09 70 98 73 93 38 53 60 04 23

**NOTE:** As there are only 16384 routes, it is possible to solve this problem by trying every route. However, Problem 67, is the same challenge with a triangle containing one-hundred rows; it cannot be solved by brute force, and requires a clever method! ;o)

In [ ]:
def compute():
  for i in reversed(range(len(triangle) - 1)):
	  for j in range(len(triangle[i])):
		  triangle[i][j] += max(triangle[i + 1][j], triangle[i + 1][j + 1])
  return triangle[0][0]

triangle = [  # Mutable
	[75],
	[95,64],
	[17,47,82],
	[18,35,87,10],
	[20, 4,82,47,65],
	[19, 1,23,75, 3,34],
	[88, 2,77,73, 7,63,67],
	[99,65, 4,28, 6,16,70,92],
	[41,41,26,56,83,40,80,70,33],
	[41,48,72,33,47,32,37,16,94,29],
	[53,71,44,65,25,43,91,52,97,51,14],
	[70,11,33,28,77,73,17,78,39,68,17,57],
	[91,71,52,38,17,14,91,43,58,50,27,29,48],
	[63,66, 4,68,89,53,67,30,73,16,69,87,40,31],
	[ 4,62,98,27,23, 9,70,98,73,93,38,53,60, 4,23],
]

print(compute())

1074

**Problem 19: Counting Sundays**

You are given the following information, but you may prefer to do some research for yourself.

- 1 Jan 1900 was a Monday.
- Thirty days has September,<br>
April, June and November.<br>
All the rest have thirty-one,<br>
Saving February alone,<br>
Which has twenty-eight, rain or shine.<br>
And on leap years, twenty-nine.<br>
- A leap year occurs on any year evenly divisible by 4, but not on a century unless it is divisible by 400.

How many Sundays fell on the first of the month during the twentieth century (1 Jan 1901 to 31 Dec 2000)?

In [ ]:
a = pd.date_range(start='1/1/1901', end='12/31/2000')
count = 0

for i in a:
    if (i.date().weekday() == 6 and i.date().day == 1):
      count += 1

print(count)

171

**Problem 20: Factorial digit sum**

n! means n × (n − 1) × ... × 3 × 2 × 1

For example, 10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800,<br>
and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.

Find the sum of the digits in the number 100!

In [ ]:
def factorial(n):
  if n < 0:
    return 'Error'
  elif n == 0:
    return 1
  else:
    return n * factorial(n-1)


def sum_of_digits(n):
  num = n
  sum = 0
  i = math.floor(math.log10(n))

  while i > -1:
    sum += num // 10**i
    num %= 10**i
    i -= 1

  return sum


print(sum_of_digits(factorial(100)))

648

**Problem 21: Amicable numbers**

Let d(n) be defined as the sum of proper divisors of n (numbers less than n which divide evenly into n).
If d(a) = b and d(b) = a, where a ≠ b, then a and b are an amicable pair and each of a and b are called amicable numbers.

For example, the proper divisors of 220 are 1, 2, 4, 5, 10, 11, 20, 22, 44, 55 and 110; therefore d(220) = 284. The proper divisors of 284 are 1, 2, 4, 71 and 142; so d(284) = 220.

Evaluate the sum of all the amicable numbers under 10000.

In [ ]:
# We first compute a table of sum-of-proper-divisors, then we use it to test which numbers are amicable.
# This approach differs from the Java implementation because trying to directly compute
# the proper-divisor-sum of each number by brute force is unacceptably slow in Python.
def compute():
	# Compute sum of proper divisors for each number
	divisorsum = [0] * 10000
	for i in range(1, len(divisorsum)):
		for j in range(i * 2, len(divisorsum), i):
			divisorsum[j] += i

	# Find all amicable pairs within range
	ans = 0
	for i in range(1, len(divisorsum)):
		j = divisorsum[i]
		if j != i and j < len(divisorsum) and divisorsum[j] == i:
			ans += i
	return str(ans)


if __name__ == "__main__":
	print(compute())

31626

**Problem 22: Names scores**

Using [**names.txt**](https://projecteuler.net/project/resources/p022_names.txt) (right click and 'Save Link/Target As...'), a 46K text file containing over five-thousand first names, begin by sorting it into alphabetical order. Then working out the alphabetical value for each name, multiply this value by its alphabetical position in the list to obtain a name score.

For example, when the list is sorted into alphabetical order, COLIN, which is worth 3 + 15 + 12 + 9 + 14 = 53, is the 938th name in the list. So, COLIN would obtain a score of 938 × 53 = 49714.

What is the total of all the name scores in the file?

In [ ]:
alphabet_scores = {
    'A':  1,
    'B':  2,
    'C':  3,
    'D':  4,
    'E':  5,
    'F':  6,
    'G':  7,
    'H':  8,
    'I':  9,
    'J': 10,
    'K': 11,
    'L': 12,
    'M': 13,
    'N': 14,
    'O': 15,
    'P': 16,
    'Q': 17,
    'R': 18,
    'S': 19,
    'T': 20,
    'U': 21,
    'V': 22,
    'W': 23,
    'X': 24,
    'Y': 25,
    'Z': 26
}

with open("p022_names.txt") as file:
  for item in file:
    # print(item)
    # print(item.replace('"', ''))
    # print(item.replace('"', '').split(','))
    # print(sorted(item.replace('"', '').split(',')))

    names = sorted(item.replace('"', '').split(','))
    # print(names)

    total_name_score = 0
    for name in names:
      for i in range(len(name)):  # Looping through each letter in a name
        total_name_score += (names.index(name) + 1) * alphabet_scores[name[i]]

    print(total_name_score)

871198282

**Problem 23: Non-abundant sums**

A perfect number is a number for which the sum of its proper divisors is exactly equal to the number. For example, the sum of the proper divisors of 28 would be 1 + 2 + 4 + 7 + 14 = 28, which means that 28 is a perfect number.

A number n is called deficient if the sum of its proper divisors is less than n and it is called abundant if this sum exceeds n.

As 12 is the smallest abundant number, 1 + 2 + 3 + 4 + 6 = 16, the smallest number that can be written as the sum of two abundant numbers is 24. By mathematical analysis, it can be shown that all integers greater than 28123 can be written as the sum of two abundant numbers. However, this upper limit cannot be reduced any further by analysis even though it is known that the greatest number that cannot be expressed as the sum of two abundant numbers is less than this limit.

Find the sum of all the positive integers which cannot be written as the sum of two abundant numbers.

In [ ]:
def compute():
	LIMIT = 28124
	divisorsum = [0] * LIMIT
	for i in range(1, LIMIT):
		for j in range(i * 2, LIMIT, i):
			divisorsum[j] += i
	abundantnums = [i for (i, x) in enumerate(divisorsum) if x > i]

	expressible = [False] * LIMIT
	for i in abundantnums:
		for j in abundantnums:
			if i + j < LIMIT:
				expressible[i + j] = True
			else:
				break

	ans = sum(i for (i, x) in enumerate(expressible) if not x)
	return str(ans)


if __name__ == "__main__":
	print(compute())

TypeError: ignored

**Problem 24: Lexicographic permutations**

A permutation is an ordered arrangement of objects. For example, 3124 is one possible permutation of the digits 1, 2, 3 and 4. If all of the permutations are listed numerically or alphabetically, we call it lexicographic order. The lexicographic permutations of 0, 1 and 2 are:

012   021   102   120   201   210

What is the millionth lexicographic permutation of the digits 0, 1, 2, 3, 4, 5, 6, 7, 8 and 9?

In [ ]:
def lexicographical_permutation(str):
  perm = sorted(''.join(chars) for chars in permutations(str))
  for i in range(len(perm)):
    if i == 999999:
      return perm[i]

str ='0123456789'
print(lexicographical_permutation(str))

2783915460

**Problem 25: 1000-digit Fibonacci Number**<br>
The Fibonacci sequence is defined by the recurrence relation:<br>
Fn = Fn−1 + Fn−2, where F1 = 1 and F2 = 1.<br>
Hence the first 12 terms will be:

F1 = 1<br>
F2 = 1<br>
F3 = 2<br>
F4 = 3<br>
F5 = 5<br>
F6 = 8<br>
F7 = 13<br>
F8 = 21<br>
F9 = 34<br>
F10 = 55<br>
F11 = 89<br>
F12 = 144

The 12th term, F12, is the first term to contain three digits.<br>
What is the index of the first term in the Fibonacci sequence to contain 1000 digits?

In [ ]:
# Because the target number is relatively small, we simply compute each Fibonacci number starting from the beginning until we encounter one
# with exactly 1000 digits. The Fibonacci sequence grows exponentially with a base of about 1.618, so the numbers in base 10 will lengthen by
# one digit after every log10(1.618) ~= 4.78 steps on average. This means the answer is at index around 4780.
def compute():
	DIGITS = 1000
	prev = 1
	cur = 0
	for i in itertools.count():
		# At this point, prev = fibonacci(i - 1) and cur = fibonacci(i)
		if len(str(cur)) > DIGITS:
			raise RuntimeError("Not found")
		elif len(str(cur)) == DIGITS:
			return str(i)

		# Advance the Fibonacci sequence by one step
		prev, cur = cur, prev + cur


if __name__ == "__main__":
	print(compute())

4782

**Problem 26: Reciprocal cycles**

A unit fraction contains 1 in the numerator. The decimal representation of the unit fractions with denominators 2 to 10 are given:

1/2	= 	0.5<br>
1/3	= 	0.(3)<br>
1/4	= 	0.25<br>
1/5	= 	0.2<br>
1/6	= 	0.1(6)<br>
1/7	= 	0.(142857)<br>
1/8	= 	0.125<br>
1/9	= 	0.(1)<br>
1/10	= 	0.1

Where 0.1(6) means 0.166666..., and has a 1-digit recurring cycle. It can be seen that 1/7 has a 6-digit recurring cycle.

Find the value of d < 1000 for which 1/d contains the longest recurring cycle in its decimal fraction part.

In [ ]:
def compute():
	ans = max(range(1, 1000), key=reciprocal_cycle_len)
	return str(ans)

def reciprocal_cycle_len(n):
	seen = {}
	x = 1
	for i in itertools.count():
		if x in seen:
			return i - seen[x]
		else:
			seen[x] = i
			x = x * 10 % n

if __name__ == "__main__":
	print(compute())

983

**Problem 27: Quadratic primes**

Euler discovered the remarkable quadratic formula:
$$ n^{2} + n + 41 $$

It turns out that the formula will produce 40 primes for the consecutive integer values $ 0 \leq n \leq 39 $. However, when $ n = 40, 40^{2} + 40 + 41 = 40(40 + 1) + 41 $ is divisible by 41, and certainly when $ n = 41, 41^{2} + 41 + 41 $ is clearly divisible by 41.

The incredible formula $ n^{2} - 79n + 1601 $ was discovered, which produces 80 primes for the consecutive values $ 0 \leq n \leq 79 $. The product of the coefficients, −79 and 1601, is −126479.

Considering quadratics of the form:<br>
&emsp;&emsp;$ n^{2} + an + b $, where $ |a| < 1000 $ and $ |b| \leq 1000 $

&emsp;&emsp;where $ |n| $ is the modulus/absolute value of $ n $

&emsp;&emsp;e.g. $ |11| = 11 $ and $ |-4| = 4 $

Find the product of the coefficients, $ a $ and $ b $, for the quadratic expression that produces the maximum number of primes for consecutive values of $ n $, starting with $ n = 0 $.